# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  # This needs to be set during build time, as it will be statically compiled into the app
  # For more information, check the .env.example file
  SKIP_AUTH: 'false'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'npm install'

  - script: |
      rm -f static/mockServiceWorker.js
    displayName: 'Delete mockServiceWorker.js before build'

  - script: |
      npm run build
    displayName: 'npm build'

  - script: |
      npm prune --production
    displayName: 'Remove dev dependencies'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'SP-Licenseapp'
      appType: 'webAppLinux'
      WebAppName: 'nexer-orebro-license-manager'
      packageForLinux: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      RuntimeStack: 'NODE|20-lts'
      StartupCommand: 'node -r dotenv/config build'
