# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - deploy-to-azure-with-adapter-node

pool:
  vmImage: ubuntu-latest

variables:
  # These placeholder values are only used for building the app
  # They need to be configured in the Azure Portal with the actual values
  # For more information, check the .env.local.example file
  AZURE_CLOUD_INSTANCE: 'https://login.microsofonline.com/'
  AZURE_TENANT_ID: 'azure-tenant-id'
  AZURE_CLIENT_ID: 'azure-client-id'
  AZURE_CLIENT_SECRET: 'azure-client-secret'
  REDIRECT_URI: 'redirect-uri'
  PUBLIC_SERVER_BASE_URL: 'server-base-url'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'npm install'

  - script: |
      npm run build
    displayName: 'npm build'

  - script: |
      npm prune --production
    displayName: 'Remove dev dependencies'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'SP-Licenseapp'
      appType: 'webAppLinux'
      WebAppName: 'license-manager-license-app-test'
      packageForLinux: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      RuntimeStack: 'NODE|18-lts'
      StartupCommand: 'node -r dotenv/config build'
